name: LipidUnet
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - tk
    - numpy
    - scikit-image
    - imageio
    - imagecodecs
    - ./imgaug/
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.5.1+cu118
    - torchvision==0.20.1+cu118
